"""
collect_amazon_listings.py
==========================
Collects REAL Amazon India product listings via the RapidAPI
"real-time-amazon-data" endpoint, to build a human-labelled evaluation set in
the actual target market.

WHY REAL LISTINGS
-----------------
Every dataset this project has trained on was generated by rules, and the
consequence was measured: F1 45.9 zero-shot on human-labelled WDC pairs,
versus 75.6 for the same model trained on 6,000 real ones. The bottleneck was
never the architecture. It was that no human ever looked at the labels.

WHY SEARCH RESULTS ARE THE RIGHT SHAPE
--------------------------------------
Searching one specific product returns a dense cluster of near-misses rather
than a clean answer. A probe for "boAt Airdopes 141" returned Airdopes 148,
141 Elite ANC, 141 Pro Buds, 163, 213, 219, a competitor's earbuds, and a
protective CASE for the 141. Random pairs from a catalog are ~all trivially
unrelated and teach nothing; these clusters are naturally dense in exactly the
cases models get wrong.

BUDGET
------
The API is on a free tier with a hard request ceiling, so the budget is an
explicit argument and the script refuses to exceed it. Each request returns
~16 listings, so ~40 queries is ~640 listings -- ample for several hundred
labelled pairs.

CREDENTIALS
-----------
The key is read from RAPIDAPI_KEY and never written to disk or committed:

    export RAPIDAPI_KEY=...        # Linux / Kaggle
    setx RAPIDAPI_KEY "..."        # Windows

Usage:
    python collect_amazon_listings.py --budget 40
    python collect_amazon_listings.py --budget 10 --queries "redmi note 13" "boAt Rockerz"
"""

import argparse
import json
import os
import time
import urllib.parse
import urllib.request
from typing import Dict, List

API_HOST = "real-time-amazon-data.p.rapidapi.com"
OUT_PATH = "data/amazon_in_listings.jsonl"

# Queries are SPECIFIC products, not categories. "earbuds" returns an
# unrelated assortment; "boAt Airdopes 141" returns a cluster of things that
# genuinely look alike, which is where matching is hard and where labels are
# worth paying for.
DEFAULT_QUERIES: List[str] = [
    # audio
    "boAt Airdopes 141", "boAt Rockerz 255 Pro", "Noise Buds VS104",
    "OnePlus Bullets Z2", "realme Buds T100", "JBL Tune 215BT",
    "Sony WH-CH520", "pTron Bassbuds", "Zebronics Sound Bomb",
    # phones
    "Redmi Note 13 5G", "Samsung Galaxy M14 5G", "OnePlus Nord CE 3 Lite",
    "iPhone 15 128GB", "vivo T2 5G", "POCO X6 Pro 5G", "Motorola G84 5G",
    # laptops
    "HP Pavilion 15 laptop", "Lenovo IdeaPad Slim 3", "ASUS Vivobook 15",
    "Dell Inspiron 15 laptop",
    # wearables
    "Noise ColorFit Pulse 2", "boAt Wave Call smartwatch",
    "Fire-Boltt Ninja Call Pro", "Apple Watch SE 2nd gen",
    # appliances / kitchen
    "Prestige mixer grinder 750W", "Philips air fryer HD9200",
    "Bajaj electric kettle 1.5L", "Havells water heater 15L",
    # tv / display
    "Mi TV 43 inch 4K", "OnePlus TV Y1S 32 inch",
    # storage
    "SanDisk Ultra 128GB pendrive", "Samsung 980 NVMe 1TB",
    "WD Elements 1TB external hard disk",
    # footwear / fashion
    "Nike Revolution 6 men", "Adidas Runfalcon 3", "Puma Softride men",
    "Campus shoes men running",
    # books / beauty / home
    "Atomic Habits book", "Mamaearth face wash", "Milton water bottle 1 litre",
]


def search(query: str, key: str, country: str = "IN", page: int = 1) -> Dict:
    params = urllib.parse.urlencode({
        "query": query, "page": str(page), "country": country,
        "sort_by": "RELEVANCE", "product_condition": "ALL",
    })
    req = urllib.request.Request(
        f"https://{API_HOST}/search?{params}",
        headers={"x-rapidapi-key": key, "x-rapidapi-host": API_HOST},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def main():
    ap = argparse.ArgumentParser(description="Collect real Amazon India listings.")
    ap.add_argument("--budget", type=int, required=True,
                    help="Hard ceiling on API requests. The script stops at this number.")
    ap.add_argument("--queries", nargs="*", default=None)
    ap.add_argument("--out", default=OUT_PATH)
    ap.add_argument("--country", default="IN")
    ap.add_argument("--sleep", type=float, default=1.2,
                    help="Seconds between calls; the free tier rate-limits aggressively.")
    args = ap.parse_args()

    key = os.environ.get("RAPIDAPI_KEY")
    if not key:
        raise SystemExit("RAPIDAPI_KEY is not set. Export it before running; "
                         "it is deliberately not stored in this file.")

    queries = (args.queries or DEFAULT_QUERIES)[:args.budget]
    print(f"budget={args.budget} requests | running {len(queries)} queries | country={args.country}")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    seen_asins, used, kept = set(), 0, 0

    with open(args.out, "w", encoding="utf-8") as fh:
        for i, query in enumerate(queries, 1):
            if used >= args.budget:
                print(f"budget reached ({used}); stopping.")
                break
            try:
                payload = search(query, key, args.country)
                used += 1
            except Exception as exc:  # noqa: BLE001
                used += 1            # a failed call still consumes quota
                print(f"  [{i:>2}/{len(queries)}] {query!r} FAILED ({exc}) -- used {used}")
                time.sleep(args.sleep)
                continue

            products = payload.get("data", {}).get("products", []) or []
            new = 0
            for p in products:
                asin = p.get("asin")
                title = (p.get("product_title") or "").strip()
                if not asin or not title or asin in seen_asins:
                    continue
                seen_asins.add(asin)
                # `query_cluster` records which search surfaced this listing.
                # Pair candidates are drawn WITHIN a cluster, because that is
                # where lookalikes live.
                fh.write(json.dumps({
                    "asin": asin,
                    "title": title,
                    "price": p.get("product_price"),
                    "original_price": p.get("product_original_price"),
                    "currency": p.get("currency"),
                    "rating": p.get("product_star_rating"),
                    "num_ratings": p.get("product_num_ratings"),
                    "url": p.get("product_url"),
                    "has_variations": p.get("has_variations"),
                    "query_cluster": query,
                }, ensure_ascii=False) + "\n")
                new += 1
                kept += 1
            print(f"  [{i:>2}/{len(queries)}] {query!r}: {len(products)} returned, {new} new "
                  f"(total {kept}) -- requests used {used}")
            time.sleep(args.sleep)

    print(f"\nWrote {kept:,} unique listings from {used} requests -> {args.out}")
    print(f"Requests remaining from a 90-call trial: ~{90 - used - 3} (3 spent on probing)")


if __name__ == "__main__":
    main()
